-- AlterTable
ALTER TABLE `pxh_fac_part_comm` MODIFY `FPC_UW_SYS_ID` INTEGER NULL,
    MODIFY `FPC_FP_SYS_ID` INTEGER NULL,
    MODIFY `FPC_POL_IDX` INTEGER NULL,
    MODIFY `FPC_FAC_IDX` INTEGER NULL;
