-- AlterTable
ALTER TABLE `pxh_fac_part_comm` MODIFY `FPC_SYS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    MODIFY `FPC_COMM_PER` DECIMAL(10, 2) NULL,
    MODIFY `FPC_COMM` DECIMAL(15, 2) NULL,
    MODIFY `FPC_COMM_LC` DECIMAL(15, 2) NULL,
    MODIFY `FPC_COMM_ORG` DECIMAL(15, 2) NULL,
    MODIFY `FPC_COMM_LC_ORG` DECIMAL(15, 2) NULL;
