-- AlterTable
ALTER TABLE `pxp_fac_place_dfn` ADD COLUMN `FPD_POL_ID` INTEGER NULL;

-- AlterTable
ALTER TABLE `pxt_fac_hdr` MODIFY `FH_UW_SYS_ID` INTEGER NULL,
    MODIFY `FH_UW_NO` VARCHAR(100) NULL,
    MODIFY `FH_POL_IDX` INTEGER NULL,
    MODIFY `FH_FAC_IDX` INTEGER NULL,
    MODIFY `FH_TOD` DATETIME(3) NULL,
    MODIFY `FH_FMD` DATETIME(3) NULL,
    MODIFY `FH_VER_NO` VARCHAR(100) NULL,
    MODIFY `FH_END_DESC` VARCHAR(2000) NULL,
    MODIFY `FH_END_TYP` VARCHAR(10) NULL,
    MODIFY `FH_END_CODE` VARCHAR(10) NULL,
    MODIFY `FH_END_TOD` DATETIME(3) NULL,
    MODIFY `FH_END_FMD` DATETIME(3) NULL,
    MODIFY `FH_FAC_END_YN` INTEGER NULL,
    MODIFY `FH_END_NO` VARCHAR(100) NULL,
    MODIFY `FH_COMP` VARCHAR(20) NULL,
    MODIFY `FH_DIVN` VARCHAR(20) NULL,
    MODIFY `FH_DEPT` VARCHAR(20) NULL,
    MODIFY `FH_LOB` VARCHAR(20) NULL,
    MODIFY `FH_COB` VARCHAR(20) NULL,
    MODIFY `FH_PROD_CODE` VARCHAR(20) NULL,
    MODIFY `FH_SINGLE_PLACE` INTEGER NULL,
    MODIFY `FH_BASIS` VARCHAR(10) NULL,
    MODIFY `FH_PERC_ALL_RSK_YN` INTEGER NULL,
    MODIFY `FH_FAC_PERC` DECIMAL(10, 2) NULL,
    MODIFY `FH_APD` DATETIME(3) NULL;
