-- CreateTable
CREATE TABLE `PXM_TTY_CVR_DFN` (
    `TCD_SYS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TCD_TD_SYS_ID` INTEGER NOT NULL,
    `TCD_PROD_CODE` VARCHAR(10) NULL,
    `TCD_SUB_PROD_CODE` VARCHAR(10) NULL,
    `TCD_CVR_CODE` VARCHAR(20) NULL,
    `TCD_PERIL_CODE` VARCHAR(20) NULL,

    PRIMARY KEY (`TCD_SYS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PXM_TTY_DFN` (
    `TD_SYS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TD_TTY_CODE` VARCHAR(100) NOT NULL,
    `TD_TTY_DESC` VARCHAR(500) NOT NULL,
    `TD_TTY_YR` VARCHAR(4) NOT NULL,
    `TD_TTY_YR_DESC` VARCHAR(500) NULL,
    `TD_FMD` DATETIME(3) NULL,
    `TD_TOD` DATETIME(3) NULL,
    `TD_LVL_NO` INTEGER NULL,
    `TD_RI_BASIS` VARCHAR(10) NULL,
    `TD_RSK_REG_YN` INTEGER NULL,
    `TD_WAR_YN` INTEGER NULL,
    `TD_LINK_TTY_CODE` VARCHAR(100) NULL,
    `TD_TTY_LINK_SYS_ID` INTEGER NULL,
    `TD_CRD` DATETIME(3) NOT NULL,
    `TD_CRU` VARCHAR(100) NOT NULL,
    `TD_UPD` DATETIME(3) NULL,
    `TD_UPU` VARCHAR(100) NULL,
    `TD_PARENT_ID` VARCHAR(100) NULL,
    `TD_PARENT_SYS_ID` INTEGER NULL,

    PRIMARY KEY (`TD_SYS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PXM_TTY_LMT_DFN` (
    `TLD_SYS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TLD_TD_SYS_ID` INTEGER NOT NULL,
    `TLD_BUS_TYP` VARCHAR(10) NULL,
    `TLD_RSK_TYP` VARCHAR(10) NULL,
    `TLD_RSK_CATG` VARCHAR(20) NULL,
    `TLD_RETN_PERC` DECIMAL(10, 2) NULL,
    `TLD_TTY_NO_LINES` INTEGER NULL,
    `TLD_TTY_LIMIT` DECIMAL(10, 2) NULL,
    `TLD_CRD` DATETIME(3) NULL,
    `TLD_CRU` VARCHAR(100) NULL,
    `TLD_UPD` DATETIME(3) NULL,
    `TLD_UPU` VARCHAR(100) NULL,
    `TLD_LVL_NO` INTEGER NULL,

    PRIMARY KEY (`TLD_SYS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PXM_TTY_SEC_DFN` (
    `TSD_SYS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TSD_TD_SYS_ID` INTEGER NOT NULL,
    `TSD_BRK_ID` VARCHAR(100) NULL,
    `TSD_SEC_ID` VARCHAR(100) NULL,
    `TSD_SHARE` DECIMAL(10, 2) NULL,
    `TSD_COMM_TYP` VARCHAR(10) NULL,
    `TSD_COMM_PER` DECIMAL(10, 2) NULL,
    `TSD_PREM_RETN_PER` DECIMAL(10, 2) NULL,
    `TSD_PREM_RETN_INT` DECIMAL(10, 2) NULL,
    `TSD_PROFIT_COMM_PER` DECIMAL(10, 2) NULL,
    `TSD_PROFIT_COMM_RATIO` DECIMAL(10, 2) NULL,
    `TSD_MGMT_EXP_PER` DECIMAL(10, 2) NULL,
    `TSD_LOSS_RETN_PER` DECIMAL(10, 2) NULL,
    `TSD_LOSS_INT_PER` DECIMAL(10, 2) NULL,
    `TSD_LOSS_REL_PER` DECIMAL(10, 2) NULL,
    `TSD_BRK_PER` DECIMAL(10, 2) NULL,
    `TSD_LEVY` DECIMAL(10, 2) NULL,
    `TSD_LEADER_FEE` DECIMAL(10, 2) NULL,
    `TSD_LEADER_YN` INTEGER NULL,
    `TSD_REL_FEQ` DECIMAL(10, 2) NULL,

    PRIMARY KEY (`TSD_SYS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
